engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 40
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Design/TooManyPublicMethods:
        enabled: false
      Design/CouplingBetweenObjects:
        enabled: false
ratings:
  paths:
    - "src/Notifynder/**.php"
exclude_paths:
  - tests/
  - spec/
  - src/migrations/
  - src/config/
